### ISSUE TITLE
Inheritance principle?

### ISSUE THREAD

**Issue by sappelhoff** [robertoostenveld/bids-validator#1]
Evaluating the current status of the `eeg_sleep` set with the EEG-bids-validator returns the expected:
``` 
~/Desktop/bids-validator/bin/bids-validator eeg_sleep/
This dataset appears to be BIDS compatible.
        Summary:              Available Tasks:        Available Modalities: 
        40 Files, 890B        sleep                                         
        1 - Subject                                                         
        1 - Session              
```
For testing reasons, I moved the `sub-01_task-sleep_eeg.json` to the root directory and renamed it to: `task-sleep_eeg.json`. According to the inheritance principle in the BIDS specification, this `*_eeg.json` file should now be valid for all subjects that do not have their own `*_eeg.json`. However, when evaluating the dataset again, I get:

```
 ~/Desktop/bids-validator/bin/bids-validator eeg_sleep/
The directory eeg_sleep/ failed an initial Quick Test.
This means the basic names and structure of the files and directories do not comply
with BIDS specification. For more info go to http://bids.neuroimaging.io/
```

This seems like a bug, especially because evaluating `ds001` works out fine --> and there we have the same situation that gives rise to an error in eeg_sleep (defining the `*_"modality".json` at the top level and using the inheritance principle)

**Comment by robertoostenveld** [comment]
can you check whether the same bug applies to mri-bids? The inheritence principle is not specific to eeg (or meg) and I have not made any changes to the validator code, nor would expect any changes needed.

**Comment by robertoostenveld** [comment]
when I remove the two task-matchingpennies files at the root level (or when I use .bidsignore), the error still appears. What makes you think it is due to inheritance errors?

**Comment by robertoostenveld** [comment]
when I delete sub-?? and replace those with sub-01 from eeg_sleep (and update participants.tsv), then the validator passes. This is with the top-level task files in place, so it does not seem an inheritance issue.

**Comment by robertoostenveld** [comment]
this fixed it

mac011> git commit -a
[bep006_eeg 0964ff8] added missing _eeg.json files
 7 files changed, 35 insertions(+)
 create mode 100644 eeg_matchingpennies/sub-05/eeg/sub-05_task-matchingpennies_eeg.json
 create mode 100644 eeg_matchingpennies/sub-06/eeg/sub-06_task-matchingpennies_eeg.json
 create mode 100644 eeg_matchingpennies/sub-07/eeg/sub-07_task-matchingpennies_eeg.json
 create mode 100644 eeg_matchingpennies/sub-08/eeg/sub-08_task-matchingpennies_eeg.json
 create mode 100644 eeg_matchingpennies/sub-09/eeg/sub-09_task-matchingpennies_eeg.json
 create mode 100644 eeg_matchingpennies/sub-10/eeg/sub-10_task-matchingpennies_eeg.json
 create mode 100644 eeg_matchingpennies/sub-11/eeg/sub-11_task-matchingpennies_eeg.json

**Comment by sappelhoff** [comment]
> What makes you think it is due to inheritance errors?

It was a first guess, do I maybe have a wrong idea about the inheritance (see below) ??

> this fixed it

Mmhh yes, I figured that fix out as well, but it seems more like a tweak to be honest ... due to the inheritance principle, these files should not be needed:

```
create mode 100644 eeg_matchingpennies/sub-05/eeg/sub-05_task-matchingpennies_eeg.json
create mode 100644 eeg_matchingpennies/sub-06/eeg/sub-06_task-matchingpennies_eeg.json
create mode 100644 eeg_matchingpennies/sub-07/eeg/sub-07_task-matchingpennies_eeg.json
create mode 100644 eeg_matchingpennies/sub-08/eeg/sub-08_task-matchingpennies_eeg.json
create mode 100644 eeg_matchingpennies/sub-09/eeg/sub-09_task-matchingpennies_eeg.json
create mode 100644 eeg_matchingpennies/sub-10/eeg/sub-10_task-matchingpennies_eeg.json
create mode 100644 eeg_matchingpennies/sub-11/eeg/sub-11_task-matchingpennies_eeg.json
```

... because at the root, we have `task-matchingpennies_eeg.json`, which should be the default for all subjects unless I specify a more concrete `*_eeg.json` at the subject level.

By adding all these `*_eeg.json` files for each subject, there is no gain in terms of information. It's just cluttering the directories, isn't it? All the information is already present in the `task-matchingpennies_eeg.json` at the root.

**Comment by robertoostenveld** [comment]
agreed. I also encountered it just now for a channels.tsv file. The error is not EEG specific (and I am not good enough as javascript programmer), I suggest you report it on https://github.com/INCF/bids-validator/issues
